name: Deploy Hugo site to Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Bootstrap
        run: |
          npm init -y
          npm install bootstrap@5.3.0

      - name: Create bootstrap symlink
        run: |
          mkdir -p assets/scss/bootstrap
          # 创建符号链接，让Hugo能够找到Bootstrap SCSS文件
          ln -sf ../../node_modules/bootstrap/scss/* assets/scss/bootstrap/ || true
          # 如果符号链接失败，直接复制文件
          cp -r node_modules/bootstrap/scss/* assets/scss/bootstrap/ 2>/dev/null || true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Create missing resource files
        run: |
          # 创建可能缺失的JS文件
          mkdir -p assets/js
          [[ ! -f assets/js/script.js ]] && echo "// Main script file" > assets/js/script.js
          [[ ! -f assets/js/bootstrap.js ]] && echo "// Bootstrap components" > assets/js/bootstrap.js
          
          # 创建可能缺失的SCSS文件
          mkdir -p assets/scss
          [[ ! -f assets/scss/adritian.scss ]] && echo "/* Main SCSS file */" > assets/scss/adritian.scss

      - name: Build
        run: hugo --minify --verbose

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
